#define __EXCEPTIONS 1 
#define __i386__ 1 
#define _X86_ 1 
#define __i386 1 
#define __i586 1 
#define __cplusplus 1 
#define __GNUC_MINOR__ 95 
#define __declspec(x) __attribute__((x)) 
#define __pic__ 1 
#define __BEOS__ 1 
#define __pentium__ 1 
#define __i586__ 1 
#define i386 1 
#define i586 1 
#define __stdcall __attribute__((__stdcall__)) 
#define __pentium 1 
#define pentium 1 
#define __INTEL__ 1 
#define __PIC__ 1 
#define __GNUC__ 2 
#define __GNUG__ 2 
#define __cdecl __attribute__((__cdecl__)) 
#define __ELF__ 1 
